### ISSUE TITLE
Fail to load plugin descriptor from file intellij-visual-studio-code-dark-plus-master.zip

### ISSUE THREAD

**Issue by dungphanxuan** [samdark/intellij-visual-studio-code-dark-plus#1]
I can't install plugin from PHPStorm 2019.1

**Comment by samdark** [comment]
I've tried with 2019.1.1. Currently have it installed. Have you built jar yourself?

**Comment by samdark** [comment]
Now it's added to official plugins store and could be installed right from IDE. If you like it, please vote there.

**Comment by samdark** [comment]
https://plugins.jetbrains.com/plugin/12255-visual-studio-code-dark-plus-theme
