### ISSUE TITLE
Change project and tab font size

### ISSUE THREAD

**Issue by ratracegrad** [samdark/intellij-visual-studio-code-dark-plus#10]
I have poor eyesight. I have changed font size for code and console but cannot find where to change the font size used to display items in project or size of font in tabs.  Can you tell me how to change the font size for both of these. Thanks

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/67676816-6adeb600-f993-11e9-8af7-fe38030977e6.png)
