### ISSUE TITLE
macOS Menu Separator Color

### ISSUE THREAD

**Issue by rynpsc** [samdark/intellij-visual-studio-code-dark-plus#12]
On macOS the menu separator has a secondary fill above and below which I don't think is intentional. Not familiar with Intellij theming so not sure what setting needs to be changed.

<img width="558" alt="macOS-menu" src="https://user-images.githubusercontent.com/5955881/72296830-7f595300-3652-11ea-9619-d328ea78a30e.png">

**Comment by samdark** [comment]
I have it slightly less visible:

![image](https://user-images.githubusercontent.com/47294/72618389-03aa1f80-394c-11ea-9b94-f016b1cabe2f.png)

323232 is the overall background color. An element should be found via http://www.jetbrains.org/intellij/sdk/docs/reference_guide/internal_actions/internal_ui_lafd.html

**Comment by samdark** [comment]
Or... it may be `ContrastBorderColor` reused.

**Comment by rynpsc** [comment]
After discovering the LaF panel I've been able to narrow in down to `PopUpMenu.background`, setting that to `#323232` resolves it.

I've also experimented with making the separator narrower with:

```
PopUpMenuSeparator.height: 13
PopUpMenuSeparator.stripeIndent: 6
PopUpMenuSeparator.stripeWidth: 1
```

<img width="352" alt="macOS-menu-v2" src="https://user-images.githubusercontent.com/5955881/72662133-423aeb00-39db-11ea-8793-4eb70eb5ad5a.png">

**Comment by reksc** [comment]
@rynpsc thanks for sharing your discovery. For me the right color code for `PopUpMenu.background` was `#242425`. Took your separator adjustments and the result is awesome.

**Comment by samdark** [comment]
@rynpsc looks awesome. Want to submit a pull request?

**Comment by samdark** [comment]
#13
