### ISSUE TITLE
Create custom plugin logo

### ISSUE THREAD

**Issue by samdark** [samdark/intellij-visual-studio-code-dark-plus#14]
Having a custom logo would be cool.

See http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html

**Comment by amstiel** [comment]
First of all, I'm love this theme and am glad to be able to use it in IDEA. Thanks 😄 

I got this pallete from official vscode [repo](https://github.com/microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_plus.json):

![image](https://user-images.githubusercontent.com/9428948/85368555-c4bd6d00-b56e-11ea-81fc-c1e67e85231e.png)

So, what about one of this variant?

![image](https://user-images.githubusercontent.com/9428948/85368859-5f1db080-b56f-11ea-85a9-e81b147ebc3c.png)

**Comment by samdark** [comment]
That's awesome! I like symmetric ones: 2 and 3. Number 3 looks more attractive.

**Comment by amstiel** [comment]
I added 3 icons to google drive. [Choose ](https://drive.google.com/drive/folders/11xQt_HNcUvvb9DkxtBHGWNaCEZiwMCSn?usp=sharing)one you like more.

**Comment by amstiel** [comment]
Or, maybe, I can make a PR... 🤔

**Comment by samdark** [comment]
PR would be awesome.

**Comment by samdark** [comment]
Checked the SVG. I guess I'll handle it.

**Comment by samdark** [comment]
Looks awesome!

![image](https://user-images.githubusercontent.com/47294/85463909-bd6a8380-b5af-11ea-84fe-91f606b078d0.png)

**Comment by samdark** [comment]
Thank you very much.

**Comment by Grawl** [comment]
I vote for number 2

**Comment by samdark** [comment]
@Grawl too late :)

**Comment by Grawl** [comment]
btw
