### ISSUE TITLE
GoLang text colors wrong

### ISSUE THREAD

**Issue by Grehgous** [samdark/intellij-visual-studio-code-dark-plus#15]
The text color scheme in this plug is not similar to the VS Code Dark+ (default) color scheme.

GoLand
![image](https://user-images.githubusercontent.com/23343347/73872924-9d177380-481e-11ea-8e65-c3836f738501.png)

VSCode
![image](https://user-images.githubusercontent.com/23343347/73872957-adc7e980-481e-11ea-8740-b9da544de8f5.png)

**Comment by samdark** [comment]
I haven't checked Golang in detail when developing the schema. It seems to be good enough for PHP, Java, JavaScript, CSS, XML, HTML.

You can adjust the schema in Settings -> Editor -> Color Scheme -> Go. Then export it in `.icls`. That would give you XML to merge into https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/resources/visual_studio_code_dark_plus.xml

**Comment by Grehgous** [comment]
@samdark In VS Code "func" and "return" are different colors, however GoLand classifies both of them as language keywords, so they share a color. Is there a workaround for making them different colors?

**Comment by samdark** [comment]
@Grehgous not that I'm aware of. That's the same with other languages. Colors are not precise but close.

**Comment by Grehgous** [comment]
PR has been started. https://github.com/samdark/intellij-visual-studio-code-dark-plus/pull/16
I can't seem to link it to this issue.

**Comment by samdark** [comment]
Thanks. I'll re-check it and merge. Then release new version. May take some time.

**Comment by samdark** [comment]
Adjusted, fixed and merged. Will be available from JetBrains after pre-moderation period (usually within days).

**Comment by feilix** [comment]
@samdark @garrettporter Hi guys! I am currently using IntelliJ IDEA version 2024.1.1 with the 2.9 version of the plugin. It appears that the issue has resurfaced. Could you please advise if there are any known problems or if further investigation is required?

![Image](https://github.com/user-attachments/assets/14981de6-522d-4342-ac01-e8edd2746676)

**Comment by samdark** [comment]
I'm not aware of it since I'm not writing golang much nowadays, so a further research would be great.

**Comment by garrettporter** [comment]
It is working for me with plugin version 2.9.0 and GoLand 2024.3.2.1.

Try re-indexing your project via `File>Repair IDE`. I have seen seen coloring like this when something is busted with indexing, but there are typically other signs of index issues such as auto-complete not working.

Also, verify `Settings>Appearance & Behavior>Appearance` and `Settings>Editor>Color Scheme` are using the plugin.

**Comment by feilix** [comment]
> It is working for me with plugin version 2.9.0 and GoLand 2024.3.2.1.
> 
> Try re-indexing your project via `File>Repair IDE`. I have seen seen coloring like this when something is busted with indexing, but there are typically other signs of index issues such as auto-complete not working.
> 
> Also, verify `Settings>Appearance & Behavior>Appearance` and `Settings>Editor>Color Scheme` are using the plugin.

![Image](https://github.com/user-attachments/assets/7de71ac7-6a75-4879-967d-3843173fc6f8)

![Image](https://github.com/user-attachments/assets/072a3e56-15ef-4912-83d7-664b495e2d53)

I have tested multiple versions of IntelliJ IDEA (2024.1.1, 2024.1.7) and GoLand (2024.1.6, 2024.2.4, 2024.3.2.1, 2024.3.4), and utilized the 'Repair IDE' function to reindex my project. Currently, the performance appears to have improved slightly. Could you please confirm if the color theme is now displaying correctly? I still feel something might be a bit off.

![Image](https://github.com/user-attachments/assets/2de2cf0f-d548-4512-a4d2-7b1897ff0a27)
