### ISSUE TITLE
python code colors 

### ISSUE THREAD

**Issue by Ceceu** [samdark/intellij-visual-studio-code-dark-plus#19]
### What the issue is?
The colors for python code in the PyCharm are not equal to the same python code in VSCode.

### Screenshots

![1](https://user-images.githubusercontent.com/11181748/75990391-9ccccf80-5ed3-11ea-8020-41c3197a36bc.png)
![2](https://user-images.githubusercontent.com/11181748/75990404-9f2f2980-5ed3-11ea-869c-8d116ba1a298.png)
![3](https://user-images.githubusercontent.com/11181748/75990417-a22a1a00-5ed3-11ea-949f-440af291e67a.png)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | latest
| IDE and version  | latest
| Operating system | Ubuntu 19.04

**Comment by samdark** [comment]
Could you adjust colors for a better match? See https://github.com/samdark/intellij-visual-studio-code-dark-plus/issues/18 on how to do it.

**Comment by skewty** [comment]
Also in PyCharm I am noticing some undesired background color in Project Tool Window.

![Screenshot from 2020-06-22 20-29-02](https://user-images.githubusercontent.com/9087223/85357857-262a0100-b4c7-11ea-8908-d50cb42b576d.png)

See `old_references` which is marked as "Excluded".  It is not selected (selected is blue).
`node_modules` also styles the same as `old_references` but it automatically marks itself as "library root" and is not marked as "Excluded".

**Comment by samdark** [comment]
@skewty that sounds like totally separate issue that is UI-related.
