### ISSUE TITLE
razor views

### ISSUE THREAD

**Issue by maciekkukuczka** [samdark/intellij-visual-studio-code-dark-plus#20]
Hi,
sometimes plugin loses colors in razor views, but sometimes is ok. Same project.

ok
![image](https://user-images.githubusercontent.com/32330973/76432777-b7abb200-63b3-11ea-8419-f9fe9449e4a4.png)

bad
![image](https://user-images.githubusercontent.com/32330973/76432784-ba0e0c00-63b3-11ea-9518-149cb538d5b3.png)

| Plugin Version   | 1.9
| IDE and version  | Rider 2020.1 EAP
| Operating system | Win 10 Pro

**Comment by samdark** [comment]
Are you sure these are OK without the VS code theme?

**Comment by maciekkukuczka** [comment]
Same view, another theme

![image](https://user-images.githubusercontent.com/32330973/76456692-a96f8d00-63d7-11ea-9195-a31aa240291b.png)

**Comment by samdark** [comment]
Interesting. Could you check if colors are correct similar to https://github.com/samdark/intellij-visual-studio-code-dark-plus/issues/18?

**Comment by maciekkukuczka** [comment]
ok, razor markup are problem.

File beginning (ok):

![image](https://user-images.githubusercontent.com/32330973/76463379-8f3bac00-63e3-11ea-84c5-af2d4c497780.png)

then is razor markups block (code is not colored):

![image](https://user-images.githubusercontent.com/32330973/76463580-ea6d9e80-63e3-11ea-9e8d-022e1e69f06d.png)

and then again html block (ok):

![image](https://user-images.githubusercontent.com/32330973/76463691-2143b480-63e4-11ea-9775-c3ab1d597275.png)

and again razor (bad):

![image](https://user-images.githubusercontent.com/32330973/76463751-43d5cd80-63e4-11ea-816e-5570c8c8162c.png)

**Comment by samdark** [comment]
So it seems that is the issue of the IDE itself, correct?

**Comment by samdark** [comment]
https://github.com/samdark/intellij-visual-studio-code-dark-plus/commit/00f06795a111cfdffeb70ab3c4503722c14e29d5 should fix it.
