### ISSUE TITLE
Hard to distinguish selected editor tab

### ISSUE THREAD

**Issue by gayanper** [samdark/intellij-visual-studio-code-dark-plus#23]
Currently it is hard to distinguish the selected editor tab when many tabs are opened.

![image](https://user-images.githubusercontent.com/7471994/84599502-d4ec9280-ae72-11ea-9610-bd9ece3c3826.png)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 1.9
| IDE and version  | 2020.1
| Operating system | Windows 10

**Comment by samdark** [comment]
I agree. Also in VSCode it is done differently:

![image](https://user-images.githubusercontent.com/47294/84836060-b38bd200-b03d-11ea-9682-0f3f9918d2ea.png)

**Comment by samdark** [comment]
Do you have some to try adjusting it? See https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/.github/CONTRIBUTING.md#ui-related for info about how.

**Comment by gayanper** [comment]
@samdark any update on this issue ? i create a PR with some fixes to make it look like vscode.

**Comment by samdark** [comment]
Yes, going to do a build and test it soon.
