### ISSUE TITLE
Python code colors in PyCharm are not the same as the Python code colors in VSCode

### ISSUE THREAD

**Issue by kmcmearty** [samdark/intellij-visual-studio-code-dark-plus#24]
### What the issue is?
Python code colors in PyCharm are not the same as the Python code colors in VSCode

### Screenshots
![Screenshot from 2020-06-16 14-01-37](https://user-images.githubusercontent.com/10493854/84811019-34b17d80-afda-11ea-864e-e5b4ce728786.png)

### How would you fix it?
Copy the color scheme from VSCode Dark+ (default dark)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 1.9
| IDE and version  | PyCharm
| Operating system |  Ubuntu 18.04

**Comment by samdark** [comment]
I don't have PyCharm so it would be very helpful if you'll try adjusting the scheme and doing a pull request. See https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/.github/CONTRIBUTING.md#code-highlighting

**Comment by samdark** [comment]
#19

**Comment by samdark** [comment]
Should be fixed with #30.
