### ISSUE TITLE
JavaScript colors - look differently!

### ISSUE THREAD

**Issue by hazartilirot** [samdark/intellij-visual-studio-code-dark-plus#28]
As I already told you when working with HTML colors look as they should. However JavaScript code isn't the same as in VS Code.

**Comment by samdark** [comment]
@hazartilirot in case you've already adjusted it, it would be really helpful if you'll share your color scheme changes. See https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/.github/CONTRIBUTING.md#code-highlighting

**Comment by rdtf1230** [comment]
same issue with him
and heres my icls
[Visual Studio Code Dark Plus.zip](https://github.com/samdark/intellij-visual-studio-code-dark-plus/files/6039996/Visual.Studio.Code.Dark.Plus.zip)

plz help me, thanks

**Comment by samdark** [comment]
@rdtf1230 your icls has no differences from theme's. Did you mean you've fixed colors and exported the color scheme?

**Comment by rdtf1230** [comment]
oh, sry it was my mistake,
i was misunderstand ur words
cuz i'm not good at English,
i thought, if i gave u my icls files, and u will see it, and u will teach me what i should do

**Comment by rdtf1230** [comment]
in javascript, it applys Dark Theme, not Dark +
here is sample
this is my intellij with dark plus theme
![image](https://user-images.githubusercontent.com/58766003/109255901-348ba200-7838-11eb-9573-faafb8d1abb8.png)

this is vscode with dark plus theme
![image](https://user-images.githubusercontent.com/58766003/109255940-4a00cc00-7838-11eb-9074-e080885b8e87.png)

what i should do??

**Comment by samdark** [comment]
Likely you've opened external file, not the project's file. Here's what I have: 
![image](https://user-images.githubusercontent.com/47294/109344347-a3401e00-787f-11eb-92f3-c96aab6dc48d.png)
