### ISSUE TITLE
Blazor components site (HTML Tags), are not colored.

### ISSUE THREAD

**Issue by maciekkukuczka** [samdark/intellij-visual-studio-code-dark-plus#29]
VSC Dark
![image](https://user-images.githubusercontent.com/32330973/88992840-a4f33480-d2e4-11ea-86d7-00798166d675.png)

Rider Dark Plus
![image](https://user-images.githubusercontent.com/32330973/88992814-973daf00-d2e4-11ea-9e1a-250449dfe0c0.png)

### Additional info
| Plugin Version   | 2.0
| IDE and version  | Rider 2020.2 EAP 8
| Operating system | Win 10 pro

**Comment by maciekkukuczka** [comment]
The solution is remove Foreground check.

![image](https://user-images.githubusercontent.com/32330973/89151483-5ef6d480-d561-11ea-88ad-c8bc037750f9.png)

**Comment by samdark** [comment]
It would be really helpful if you'll share your color scheme changes. See https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/.github/CONTRIBUTING.md#code-highlighting

**Comment by gerwim** [comment]
@maciekkukuczka Thanks! Disabling inheritance and removing the foreground check worked for me.

@samdark I've cloned the repo but it seems Rider doesn't know how to run this (wanted to submit a PR). I'll probably need IntelliJ for it :-/.

**Comment by samdark** [comment]
You can export your current color scheme and attach it here. That may be enough.

**Comment by gerwim** [comment]
Thanks @samdark! I've attached the file.
[visual_studio_code_dark_plus.zip](https://github.com/samdark/intellij-visual-studio-code-dark-plus/files/5257461/visual_studio_code_dark_plus.zip)

Looking at the diff, it seems like this is the fix:
```
    <option name="ReSharper.ASP_NET_RAZOR_CODE_BLOCK">
      <value>
        <option name="BACKGROUND" value="1e1e1e" />
        <option name="EFFECT_TYPE" value="5" />
      </value>
    </option>
```

**Comment by samdark** [comment]
Applied it to master. It will get into next plugin release.
