### ISSUE TITLE
Missing keyword highlighting colors

### ISSUE THREAD

**Issue by lkiran** [samdark/intellij-visual-studio-code-dark-plus#34]
### What the issue is?
Java highlighting colors are not consistent in terms of 
+ Imports
+ Control keywords like `if`, `else`, `for`, `return`

### Screenshots
![image](https://user-images.githubusercontent.com/15219328/101994248-0f27d700-3cd2-11eb-9699-1139bce10c84.png)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.2
| IDE and version  | 2020.3

**Comment by samdark** [comment]
Would be great if you'll adjust colors locally and export color scheme.

**Comment by amstiel** [comment]
This is IDEA issue. Not the theme. 😞 

IDEA can not highlight specific keywords (`import`, `export`, `switch`, `if`, etc.) separately for now. Currently, it uses `KEYWORD` group color for all syntax keywords. 

There is an [issue](https://youtrack.jetbrains.com/issue/IDEABKL-5473) about it. 😉

**Comment by samdark** [comment]
Closing since can't fix it from plugin's side.
