### ISSUE TITLE
Add link to original theme

### ISSUE THREAD

**Issue by GauthierPLM** [samdark/intellij-visual-studio-code-dark-plus#4]
It would be nice to have a link to the original theme (Visual Studio Code Dark Plus) or a little explanation about where it comes from for people who are curious like me.

**Comment by samdark** [comment]
You mean https://plugins.jetbrains.com/plugin/12255-visual-studio-code-dark-plus-theme?

The link is right in the header:

![image](https://user-images.githubusercontent.com/47294/60715463-bcb38a00-9f25-11e9-98d9-1e5513f6e6a7.png)

**Comment by GauthierPLM** [comment]
The plugin description says "Dark theme inspired by Visual Studio Code Dark Plus", so I guess "Visual Studio Code Dark Plus" must be a theme available for VS Code. however, I was not able to find it.
If it's the default theme, my mistake. I am a bit confused about it.

**Comment by samdark** [comment]
It is a default theme.

**Comment by samdark** [comment]
Clarified it in readme and plugin meta.
