### ISSUE TITLE
[Feature]Shows the code affected by the current curly braces.

### ISSUE THREAD

**Issue by qinywolf** [samdark/intellij-visual-studio-code-dark-plus#40]
### What the issue is?
**Feature suggestion**
### Screenshots
![Snipaste_2021-04-17_21-36-39](https://user-images.githubusercontent.com/70853687/115115196-9f01c880-9fc5-11eb-9fdc-b2bb17c0c91e.png)
### Function description
Sorry, my native language is not English, which may cause deviations in description.
My version is Idea 2021.1. In the default Darcula theme, when the cursor is on the curly brace, the code affected by the curly brace will be displayed with a blue line on the left.
Request to add this feature in Visual Studio Code Dark Plus Theme as well.
Thank you!

**Comment by samdark** [comment]
Looks interesting. Do you have an idea on where it could be configured in the color scheme?

**Comment by qinywolf** [comment]
> Looks interesting. Do you have an idea on where it could be configured in the color scheme?

I tried to find this setting, but unfortunately I couldn't find it. Maybe I need to contact Jetbrains（；´д｀）ゞ

**Comment by qinywolf** [comment]
> Looks interesting. Do you have an idea on where it could be configured in the color scheme?
it is hear ! lol !

![image](https://user-images.githubusercontent.com/70853687/115714967-45751180-a3aa-11eb-9a97-14bea8f09208.png)
