### ISSUE TITLE
color is wrong in some place 

### ISSUE THREAD

**Issue by JimmyWang** [samdark/intellij-visual-studio-code-dark-plus#41]
### What the issue is?
color is wrong in some place 
### Screenshots
![image](https://user-images.githubusercontent.com/6657454/115485554-8e807500-a287-11eb-878d-f2513d34fb23.png)
![image](https://user-images.githubusercontent.com/6657454/115485594-a0621800-a287-11eb-9a6f-13e8c5de1c57.png)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.4
| IDE and version  |  Goland 2020.1
| Operating system | windows 10 enterprise 19042.804

**Comment by samdark** [comment]
Interesting...

![image](https://user-images.githubusercontent.com/47294/115531323-4ec48800-a29d-11eb-86cb-9e7b3773f320.png)

Have you restarted IDE after installing the theme?

**Comment by JimmyWang** [comment]
> Interesting...
> 
> ![image](https://user-images.githubusercontent.com/47294/115531323-4ec48800-a29d-11eb-86cb-9e7b3773f320.png)
> 
> Have you restarted IDE after installing the theme?

YES，already restarted GOLAND.

**Comment by samdark** [comment]
So everything is alright?

**Comment by JimmyWang** [comment]
> So everything is alright?

NO, the same as before ...

**Comment by JimmyWang** [comment]
need I provide some infos, such as logs...

**Comment by samdark** [comment]
Tried with latest GoLand 2020.1.1 just in case. That's what I got right after theme is applied:

![image](https://user-images.githubusercontent.com/47294/115910753-e7156500-a475-11eb-91b8-c82b74840476.png)

I'm not sure what's different in your case and it's likely that it should be fixed by JetBrains so please report it to:  https://youtrack.jetbrains.com/issues/WI

**Comment by JimmyWang** [comment]
> Tried with latest GoLand 2020.1.1 just in case. That's what I got right after theme is applied:
> 
> ![image](https://user-images.githubusercontent.com/47294/115910753-e7156500-a475-11eb-91b8-c82b74840476.png)
> 
> I'm not sure what's different in your case and it's likely that it should be fixed by JetBrains so please report it to: https://youtrack.jetbrains.com/issues/WI

okay, pls close this issue if you want to
