### ISSUE TITLE
The color scheme in clion/C++ is not consistent with VS Code.

### ISSUE THREAD

**Issue by SkyRunner123** [samdark/intellij-visual-studio-code-dark-plus#42]
### What the issue is?
The color scheme seems to be different from the latest version of VS code.
### Screenshots
clion:
![image](https://user-images.githubusercontent.com/62864933/117423520-66656700-af53-11eb-8f7f-bdd4b2a03a41.png)
vs code:
![image](https://user-images.githubusercontent.com/62864933/117423634-839a3580-af53-11eb-85e3-117961be4f8a.png)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.4
| IDE and version  | clion: 2020.3.4;   vs code: 1.55.2
| Operating system | window 10

**Comment by samdark** [comment]
Thanks for report. I'm not clion user so your help would be great:

1. Adjust colors in your IDE for C++ (Settings -> Editor -> Color Scheme).
2. Try not to change general colors since these are used for other languages.
3. Export color scheme as icls and attach it here.

**Comment by SkyRunner123** [comment]
There are a lot of restrictions in clion, and it can't be completely consistent with the color matching in vscode. For example, many keywords are linked together and can't be colored separately. I've done my best to do some of them. I hope they are useful to you!
[Visual Studio Code Dark Plus.zip](https://github.com/samdark/intellij-visual-studio-code-dark-plus/files/6444791/Visual.Studio.Code.Dark.Plus.zip)

**Comment by samdark** [comment]
Awesome. I'll check it.

**Comment by samdark** [comment]
I'll include the colors into next release. Sorry that it took that much time.
