### ISSUE TITLE
Code coverage lines are not shown when the theme is active

### ISSUE THREAD

**Issue by andreibaptista** [samdark/intellij-visual-studio-code-dark-plus#44]
### What the issue is?

Code coverage lines are not shown when the theme is active.

### Screenshots
Active:
![image](https://user-images.githubusercontent.com/9382192/131851712-f559ff43-0068-4567-8bc3-b6239b10fa69.png)

Now, with another theme active:

![image](https://user-images.githubusercontent.com/9382192/131851843-5978f0df-af74-458e-952f-64048c6e2d13.png)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.5
| IDE and version  | 

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), io.heidou.codesearch (1.1.0), com.mallowigi (38.0.0), CheckStyle-IDEA (5.55.1), String Manipulation (8.15.203.000.3), org.jetbrains.plugins.go (212.4746.92), aws.toolkit (1.31-212), zielu.gittoolbox (212.7.6), com.chrisrm.idea.MaterialThemeUI (6.8.2), com.samdark.intellij-visual-studio-code-dark-plus (2.5)
Kotlin: 212-1.5.10-release-IJ4746.92
| Operating system |

**Comment by samdark** [comment]
Would you please check colors defined in the scheme for these?

**Comment by andreibaptista** [comment]
I think the problem are in that sector...

By default, the other plugins are all checked as background, and in the other hand, the Visual studio code dark plus, are seted by default in Foreground, and it makes the color of the lines fade away.

Github dark material:
![image](https://user-images.githubusercontent.com/9382192/131884673-168a982c-086d-4d20-9e2f-b89b880ced93.png)

Visual studio code dark plus -> Foreground by default
![image](https://user-images.githubusercontent.com/9382192/131884734-220ba583-ea83-451a-b29a-d6fc7be2fea3.png)

Now, I can see the lines, all are working fine!

**Comment by samdark** [comment]
I see. Would you please attach your exported color scheme with these modifications? Thanks.

**Comment by samdark** [comment]
Solved in master.
