### ISSUE TITLE
Python varible theme is not matching VS Code

### ISSUE THREAD

**Issue by zhiyaot** [samdark/intellij-visual-studio-code-dark-plus#46]
### What the issue is?
The theme for python in both CLion and PyCharm is not exactly matching VSCode

### Screenshots
![image](https://user-images.githubusercontent.com/32091356/149650458-efbf0505-414a-4bee-b520-44a6d7db1827.png)
^^^ this is in CLion

![image](https://user-images.githubusercontent.com/32091356/149650501-5ad9ef03-d6e4-4b99-bfd8-243ca6ddd557.png)
^^^ in VSCode

Which is more concerning, or I suspect a bug from Jetbrain

![image](https://user-images.githubusercontent.com/32091356/149650550-8f249118-85fe-42ad-ad7c-dfd1e334e0f9.png)
^^^ This is what the setting page gives as a preview of the python code

![image](https://user-images.githubusercontent.com/32091356/149650584-4af73551-de29-4a97-9bd7-6ea2fead024a.png)
^^^ Copied to the editor, notice that the light blue for local variable x is gone

### How would you fix it?
I have no idea :(

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.5
| IDE and version  |  CLion 2021.3.2
| Operating system | Window 10, Ubuntu 20.04

**Comment by samdark** [comment]
Thanks for reporting. Would you please attach the file in question?

**Comment by zhiyaot** [comment]
```python
import argparse
import logging
import pathlib
import sys
from datetime import date

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='bert_gen', prog='bert_gen')
    parser.add_argument("baseDir", help='Directory of the file_gen.tcl output')
    parser.add_argument("--log")
    parser.add_argument('--version', action='version', version='%(prog)s 1.0')
    args = parser.parse_args()

    logger = logging.getLogger('bert_gen')

    if sys.platform.startswith('win32'):
        print("Detected Windows System")

    elif sys.platform.startswith('linux'):
        print("hahha")
```
```python
@decorator(param=1)
def f(x):
    """
    Syntax Highlighting Demo
    @param x Parameter

    Semantic highlighting:
    Generated spectrum to pick colors for local variables and parameters:
     Color#1 SC1.1 SC1.2 SC1.3 SC1.4 Color#2 SC2.1 SC2.2 SC2.3 SC2.4 Color#3
     Color#3 SC3.1 SC3.2 SC3.3 SC3.4 Color#4 SC4.1 SC4.2 SC4.3 SC4.4 Color#5
    """

    def nested_func(y):
        print(y + 1)

    s = ("Test", 2+3, {'a': 'b'}, f'{x!s:{"^10"}}')   # Comment
    f(s[0].lower())
    nested_func(42)

class Foo:
    tags: List[str]

    def __init__(self: Foo):
        byte_string: bytes = b'newline:\n also newline:\x0a'
        text_string = u"Cyrillic Я is \u042f. Oops: \u042g"
        self.make_sense(whatever=1)

    def make_sense(self, whatever):
        self.sense = whatever

x = len('abc')
print(f.__doc__)
```

**Comment by samdark** [comment]
Thanks. I can't promise I'll look into it anytime soon so anyone that has time and can help adjusting the color schema, you're very welcome.
