### ISSUE TITLE
Text is black in some places

### ISSUE THREAD

**Issue by ChrisZevenbergenNavara** [samdark/intellij-visual-studio-code-dark-plus#48]
### What the issue is?
Color of text in certain places is black and therefore barely readable.

### Screenshots
![image](https://user-images.githubusercontent.com/79903260/152129795-9a7aadb6-d217-41a3-b7c9-7b287bf8968e.png)
![image](https://user-images.githubusercontent.com/79903260/152129854-75aa6a14-7a48-48c6-a02e-b6486b097855.png)
![image](https://user-images.githubusercontent.com/79903260/152129897-1ebd99c0-1e47-44ff-9f90-4b810023a240.png)

### How would you fix it?
I'm not too sure yet. I will look into it. I have no experience with customizing themes just yet.

### Additional info

Plugin version 2.5
Jetbrains Rider 2021.3.3
MacOS Big Sur 11.6.2

**Comment by samdark** [comment]
Interesting. Have you re-started IDE? Sometimes theme isn't fully applied before restarting IDE>

**Comment by ChrisZevenbergenNavara** [comment]
Yeh, it's been like this for a while. It started when I upgraded to RIder 2021.3.1. On 2021.2 it works fine.

**Comment by samdark** [comment]
I see. I might get to it but not too soon. Therefore, I'll gladly accept a pull request if you have time to check it. See how it was done for alike issues with UI: https://github.com/samdark/intellij-visual-studio-code-dark-plus/issues/12#issuecomment-575641401

**Comment by samdark** [comment]
Re-checked with latest version to be released. Can't reproduce it.
