### ISSUE TITLE
Add "Editor Color Schemes" to plugin's categories

### ISSUE THREAD

**Issue by GauthierPLM** [samdark/intellij-visual-studio-code-dark-plus#5]

**Comment by samdark** [comment]
I'm not sure what are plugin categories. Would you please elaborate?

**Comment by GauthierPLM** [comment]
On the plugin' settings page you can choose the categories. Currently, the plugin is in "UI" and "Theme" categories, but as it also provides a color scheme, I think it would be nice to add it to the corresponding category.

**Comment by samdark** [comment]
Well, not really. I can choose "UI" but "Theme" seems to be inferred from source code.

![image](https://user-images.githubusercontent.com/47294/60720790-8598a500-9f34-11e9-912a-a3b2156e3284.png)

Likely it is `bundledColorScheme` from `plugin.xml` as could be seen here: https://github.com/rainglow/jetbrains/blob/master/META-INF/plugin.xml#L16

**Comment by samdark** [comment]
Done. https://github.com/samdark/intellij-visual-studio-code-dark-plus/commit/f6ecd55d53acdc8f9fbd187223c8a8d63afa8464 Will be reflected on the website with the next release.
