### ISSUE TITLE
Tabs do not get the color

### ISSUE THREAD

**Issue by sandynicotcisneros** [samdark/intellij-visual-studio-code-dark-plus#50]
### What the issue is?
Not all tabs are not coloring, even with the configuration set up. It is only coloring when the tab gets the focus.

### Screenshots
![image](https://user-images.githubusercontent.com/41551602/168594375-7148aea6-7e6b-47c9-beee-9e97559e5218.png)
![image](https://user-images.githubusercontent.com/41551602/168594417-7b12da74-bd68-44f9-a2ec-5913eeb920b0.png)
![image](https://user-images.githubusercontent.com/41551602/168594434-c4a5d18a-dab8-4142-a4f8-e1c636a68943.png)
![image](https://user-images.githubusercontent.com/41551602/168594447-4c5d2bc6-a4a9-47b8-89ed-9ac81ee1d643.png)
![image](https://user-images.githubusercontent.com/41551602/168594464-f189c7dc-13d1-4e6d-9fdc-cf673947c78f.png)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 1.?
| IDE and version  | Datagrip 2022.1.3
| Operating system | Windows

**Comment by samdark** [comment]
Re-checked it with version to be released. Tabs are colored properly:

<img width="496" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/47294/020f3b26-64ad-4cec-8d1d-9a800149505f">
