### ISSUE TITLE
Console background is inconsistent

### ISSUE THREAD

**Issue by guihigashi** [samdark/intellij-visual-studio-code-dark-plus#51]
### What the issue is?

The console background color is inconsistent. As shown below, some symbols have darker background.

### Screenshots

Default:
![image](https://user-images.githubusercontent.com/7825153/169046720-ceb95229-5e22-4711-9401-0c94255055d4.png)

### How would you fix it?

Maybe this value is inherited, but changing `Console colors > Console > Background > Background` from `2B2B2B` to `1D1D1D` makes
the background match, and it also matches the background of files. This is the one setting i always change when installing the plugin. 

`1D1D1D`:
![image](https://user-images.githubusercontent.com/7825153/169047112-fd43e31e-a87a-4aa6-8c6f-66e55bde8709.png)

The other way would be to change the background of those symbols to match the `2B2B2B`, but i think this way is more complicated.

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.5
| IDE and version  | 
| Operating system |

**Comment by samdark** [comment]
Thanks for reporting. Do you have some time for a pull request? i.e. change the color, export it, find out the difference and add it to https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/resources/visual_studio_code_dark_plus.xml
