### ISSUE TITLE
Tab color in new UI

### ISSUE THREAD

**Issue by rogama25** [samdark/intellij-visual-studio-code-dark-plus#55]
### What the issue is?
The active tab color is not different from the color of the other tabs in the new UI that will be released in 2022.3

### Screenshots
![image](https://user-images.githubusercontent.com/11318350/201079565-648e1d3b-5a57-4e77-bda6-4717d75f1eea.png) (Active tab is the second one)

### How would you fix it?

I would update the theme colors. If I have some spare time, I will create a PR for this Soon(TM)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.6
| IDE and version  | IntelliJ IDEA Community 2022.3 EAP
| Operating system | Ubuntu 22.04

**Comment by burya4ok** [comment]
Could some one take this bug and create PR with fix?

**Comment by samdark** [comment]
That's not only tab color in new UI that is missing.

When no file is opened, there's no distinction between panels and the main area which is a bit confusing:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/47294/206843125-b589d520-f291-4c0b-a82f-51a1414696f5.png">

**Comment by melisekm** [comment]
Temporal workaround would be to install another theme like Material Theme UI, which changes menu style and then use VSCode theme with it. 
<img src="https://user-images.githubusercontent.com/46221266/210644281-292a7839-a6af-4a90-92a3-b74914752842.png" alt="img1" width="300"/>
<img src="https://user-images.githubusercontent.com/46221266/210645106-033044ed-0278-4376-8c53-05bd8c73d26a.png" alt="img2" width="300"/>

**Comment by wylu1037** [comment]
You can intsall the plugin file, then unzip downloaded file, locate visual_studio_code_dark_plus.theme.json, follow the below picture, then backup IDEA, intsall plugin from the disk.
![image](https://user-images.githubusercontent.com/114670506/212208491-1ff52307-cdfc-44a6-b1f3-c82d6c496461.png)

**Comment by samdark** [comment]
@wylu1037 would you please make a pull request out of it? Thanks.
