### ISSUE TITLE
Tab color in new UI is wrong in some IDEs

### ISSUE THREAD

**Issue by samdark** [samdark/intellij-visual-studio-code-dark-plus#57]
IDEA 2023.1.1 (Ultimate Edition):

![68747470733a2f2f692e696d6775722e636f6d2f6e516b6a726a312e706e67](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/47294/fc8c157a-ebc2-4255-83bb-3be6afb6c27b)

WebStrom 2023.1.1: 

![237209334-0125df52-e980-4ab3-80d2-b0123d0ab696](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/47294/9fa484d9-6c8b-4260-acf3-63b0daa3720b)

Rider:

![237209348-85b00a81-28fb-4c62-b87a-099ebe33cb4c](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/47294/60cf713c-e2a6-4e02-83cb-61e876cbb688)

See #56

**Comment by jsodeman** [comment]
I can't recall the details but when I was looking for a way to change the tab highlighting I came across a few  tickets in YouTrack regarding the new UI ignoring some of the tab related color scheme settings.

**Comment by Fokrychel** [comment]
hah, same question, werid

**Comment by jsodeman** [comment]
This is the YouTrack ticket I was referring to:

https://youtrack.jetbrains.com/issue/IDEA-307289/Selected-Tab-Background-Color-not-working-in-new-UI

**Comment by rtm516** [comment]
I get this with the 'old' UI on IntelliJ Idea 2023.1.1 since the 2.7 release and this commit https://github.com/samdark/intellij-visual-studio-code-dark-plus/commit/47c3184908ff90d951e462fe89e884a2d2777f37

**Comment by patrickteng** [comment]
Same issue here on PhpStorm. Needed to use a plugin to override it

![Screenshot 2023-05-11 at 11 14 28 AM](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/13133091/8d5fd336-fd0d-49aa-a99d-c55078116ed1)

**Comment by jsodeman** [comment]
@patrickteng This one? https://plugins.jetbrains.com/plugin/9562-active-tab-highlighter

**Comment by patrickteng** [comment]
> @jsodeman yes, currently using that, but still slightly buggy (it goes to default pink color if i navigate to other apps, but reverts to the color i set after clicking on another tab). Still better than the bright blue on the vsc-dark-plus currently.

**Comment by samdark** [comment]
Alright. I can reproduce it with PhpStorm 2023.1.1 and new UI:

<img width="571" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/47294/c32cc47e-1c3c-416f-bb50-0cf7e5ae472a">

**Comment by maples3** [comment]
For what it's worth, I'm also seeing this in PhpStorm 2023.1.1 with the old UI enabled, after updating the theme plugin to version 2.7.
![image](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/15505712/1a0f7a09-3f34-40f8-82e4-6991a9462412)

Manually downloading and reinstalling version 2.6 fixes the issue

**Comment by jsodeman** [comment]
I just updated to 2023.1.2 in both WebStorm and Rider and it looks like the active tab identification is fixed in both.

WebStorm
![image](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/2388842/9bb7b0b9-09a0-4eda-9bcc-e493af498250)

Rider
![image](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/2388842/3c69a2dd-3af8-44a3-b916-1052b45e7e46)

**Comment by samdark** [comment]
PhpStorm 2023.1.2.

Old UI:

<img width="383" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/47294/3a5db644-7a0f-4afb-ae88-96a669955683">

New UI:

<img width="421" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/47294/ce73956a-64ec-4a74-b567-4186010ebc0d">

**Comment by jsodeman** [comment]
@samdark That's progress though right? :-) At least there's a version that works for each.

**Comment by MichalVasut** [comment]
> PhpStorm 2023.1.2.
> 
> Old UI:
> 
> <img alt="image" width="383" src="https://user-images.githubusercontent.com/47294/239385884-3a5db644-7a0f-4afb-ae88-96a669955683.png">
> New UI:
> 
> <img alt="image" width="421" src="https://user-images.githubusercontent.com/47294/239385986-ce73956a-64ec-4a74-b567-4186010ebc0d.png">

Same happens in `PyCharm 2023.1.2 (Professional Edition)`

**Comment by ooooo84** [comment]
This issue is came back after upgrade to 2023.1.3, tested in IDEA and WebStorm. The UI is same as the initial post.
Downgrade to 2.6 and use old UI works fine.

**Comment by DonPuh** [comment]
After updating PhpStorm to version 2023.1.3 the problem returned.

![bug_color_tabs](https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/77413974/73d385f3-1a11-4912-8aa8-abe24dd4e4a7)

**Comment by samdark** [comment]
Will be fixed in the upcoming release.
