### ISSUE TITLE
[2023.2] Terminal and editor are missing styling

### ISSUE THREAD

**Issue by gerwim** [samdark/intellij-visual-studio-code-dark-plus#59]
### What the issue is?
The editor and terminal are no longer styled.
### Screenshots
<img width="1980" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/1841721/69599d3e-25ae-44a5-abfa-bfda2901d14d">

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.8
| IDE and version  | 2023.2
| Operating system | MacOS and Windows

**Comment by samdark** [comment]
Would you please check if color scheme is still selected correctly?
