### ISSUE TITLE
The action "Highlight Usages in File" does not highlight all usages

### ISSUE THREAD

**Issue by ojhawkins** [samdark/intellij-visual-studio-code-dark-plus#65]
### What the issue is?
When using `Highlight Usages in File` it does not highlight all usages.
<img width="751" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/2830243/4ce62e35-ba27-4b3d-ad56-75a4a2ba54a3">

### Screenshots
This is the inbuilt dark mode when I highlight `value`
<img width="292" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/2830243/a3896c61-6e03-4641-84f2-0a680b95da92">

This is what the theme looks like
<img width="287" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/2830243/ddc3bd5c-2b78-4e9c-914c-d341c666e411">

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.8
| IDE and version  | IntelliJ IDEA 2024.1 (Ultimate Edition) Build #IU-241.14494.240
| Operating system | macOS 14.4.1 (23E224)

**Comment by samdark** [comment]
Interesting. Any idea what setting is used for it?

**Comment by ojhawkins** [comment]
I did work it out, I'll create a PR with the fix.

**Comment by ojhawkins** [comment]
Hi Alexander, I do not have perms to push a branch.

This is what it looks like:

<img width="1683" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/2830243/6fab4805-cd72-4144-893f-bed8437ea6c3">

Happy to push if you grant me access or these are the changes:

<img width="1250" alt="image" src="https://github.com/samdark/intellij-visual-studio-code-dark-plus/assets/2830243/3fa6416c-22a3-42ae-abe9-b04a32aef883">

I don't think they are strictly the right colours but can dig them up if you would like.

**Comment by samdark** [comment]
> Hi Alexander, I do not have perms to push a branch.

Fork first. Pull requests are created from your own repos.

**Comment by samdark** [comment]
Solved in master.
