### ISSUE TITLE
is it lighter than vscode dark+?

### ISSUE THREAD

**Issue by songxianpeng** [samdark/intellij-visual-studio-code-dark-plus#7]
IDEA:
![image](https://user-images.githubusercontent.com/9303424/61574859-c4635900-aaf7-11e9-8709-9ff99cf5027d.png)
VSCode:
![image](https://user-images.githubusercontent.com/9303424/61574869-d6dd9280-aaf7-11e9-9261-b4899a8f3931.png)

**Comment by samdark** [comment]
Should not be. You can look for exact colors in VS code XML files in the installation directory. Font rendering seems to be different though.
