### ISSUE TITLE
2.9 C# highlighting

### ISSUE THREAD

**Issue by lofcz** [samdark/intellij-visual-studio-code-dark-plus#72]
### What the issue is?

I'm a long-term (don't even know how many years) user of your theme. Recently, v 2.9 included this change: https://github.com/samdark/intellij-visual-studio-code-dark-plus/commit/c97581ae94d9ca4a13bd2d97e34215d971614f5a

This broke some colors in the theme for me - is this something I can revert to the 2.8 settings? I like the other changes, but for now, I've reverted to 2.8. 

Can I export the old scheme, update the plugin, and then override the color changes? So far the only way I've discovered is doing this:
![image](https://github.com/user-attachments/assets/15ee39a1-3fb0-485f-941d-3853578dbfdb)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2:9
| IDE and version  | 2024.2.2
| Operating system | Windows

**Comment by samdark** [comment]
What was broken exactly?

**Comment by lofcz** [comment]
Enums, interfaces (now light yellow instead of green as on the screenshot), properties/fields are white instead of light blue, and possibly some other colors.

**Comment by samdark** [comment]
I see. The changes are to make C# highlighting closer to how it is in VSCode's theme. 

> Can I export the old scheme, update the plugin, and then override the color changes? So far the only way I've discovered is doing this

That's exactly how it's done.

**Comment by lofcz** [comment]
It would be great to warn and/or make colors changes optional, some forks are really used to the ones they use.

**Comment by samdark** [comment]
Thanks. I'll think about how to do it in the future.

**Comment by lofcz** [comment]
FYI I've forked the theme in case someone else is just as used to the old c# colors as I am. This is clearly labeled as a fork and makes no attempts to steal any attention from the upstream. I won't be sharing this anywhere but this issue: https://github.com/lofcz/intellij-visual-studio-code-dark-plus
