### ISSUE TITLE
After IntelliJ update 2024.2, the background is white

### ISSUE THREAD

**Issue by cosimosacco** [samdark/intellij-visual-studio-code-dark-plus#73]
### What the issue is?
As per title, the background appears white after IntelliJ 2024.2 update.
I've already tried disabling/re-enabling, uninstalling/re-installing, restarts, etc...

### Screenshots
![image](https://github.com/user-attachments/assets/962d605b-928f-468e-926f-0f4feeb924ba)

### How would you fix it?
N/A

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.9.0
| IDE and version  | 2024.2
| Operating system | Windows 10

**Comment by samdark** [comment]
Interesting. Looks like the editor color schema isn't applied. Would you please re-check if it's selected?

![image](https://github.com/user-attachments/assets/b58cb232-f321-4959-8f0b-b498b75ba436)

**Comment by wimdavies** [comment]
@samdark nice one, yes you're correct, it is not selected in Settings > Color Scheme:
<img width="691" alt="image" src="https://github.com/user-attachments/assets/2d94ae59-e756-49d2-b9c8-88cd3b16eaab">
This is despite it being selected in the 'Themes' dialog.

**Comment by wimdavies** [comment]
Manually selecting it as the scheme in the Editor settings successfully applies it to files.

**Comment by wimdavies** [comment]
Hi @samdark, _is_ this completed though? Is it the behaviour at risk of happening again? Can it be fixed automatically for users who don't know about this manual solution?
Happy to contribute if that would be useful

**Comment by samdark** [comment]
It happens from time to time but it's not related to the theme itself. It's something within IDE so I cannot fix it.

**Comment by cosimosacco** [comment]
Also in my case, the color scheme was not selected. Thanks for the troubleshoot.

**Comment by wimdavies** [comment]
@samdark understandable, and I'm sorry, that must be frustrating. Is it perhaps worth leaving a note to that effect somewhere in the readme and on the plugin listing with IntelliJ? Via the reviews, I can see other users experiencing this issue  periodically, and it seems a shame for something that's out of your hands to be affecting your review score and the reception of your hard work.

**Comment by samdark** [comment]
Yes. Maybe. I'll think about how to note it. Thanks.

**Comment by wimdavies** [comment]
I've left a review on Marketplace that notes the fix and directs people to this discussion, FWIW. Hope that helps.
