### ISSUE TITLE
In pycharm 2019.2  Abnormal color of title bar

### ISSUE THREAD

**Issue by a616781689** [samdark/intellij-visual-studio-code-dark-plus#8]
![image](https://user-images.githubusercontent.com/31605348/62002212-f72dd280-b131-11e9-8fae-8c388bb10a78.png)

Platform：Windows10 1903

**Comment by samdark** [comment]
Before menu was merged, that was on purpose to have distinct color. Now it looks controversial.

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/62252382-5f630980-b3fb-11e9-95fc-76ba4e4551aa.png)

Re-checked. It could be adjusted only along with menus:

![image](https://user-images.githubusercontent.com/47294/62252509-bbc62900-b3fb-11e9-8550-162e0b2bcbec.png)

I like the current variant better usability-wise.

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/62252633-13fd2b00-b3fc-11e9-85b9-41c53d1b737e.png)

**Comment by a616781689** [comment]
In 2019.2.2 Jetbrains fix this bug
