### ISSUE TITLE
Ubuntu 19 Intellij 2019.1.4 cannot import settings

### ISSUE THREAD

**Issue by mikey-t** [samdark/intellij-visual-studio-code-dark-plus#9]
On Ubuntu 19 Intellij 2019.1.4 I cannot import settings. If I select File -> Import Settings and select the jar file for this theme, I get the following error:

The file /home/johndoe/Downloads/intellij-visual-studio-code-dark-plus.jar contains no settings to import.
Please make sure you have generated the file using 'File|Export Settings' feature.

**Comment by samdark** [comment]
You don't need to import anything: https://github.com/samdark/intellij-visual-studio-code-dark-plus#installation

**Comment by mikey-t** [comment]
Thanks, my bad. Seems like I installed it via import settings last time around. I downloaded it directly from https://plugins.jetbrains.com/plugin/12255-visual-studio-code-dark-plus-theme and it doesn't really do any hand holding for intellij n00bs like myself. Installing it from the plugins UI is going into my notes.
